name: CommandTracker
version: 2.0.0
main: RTG\Tracker\CommandTracker
api: [3.0.0, 4.0.0]
author: IG
commands:
  check:
    description: "Check CommandTracker"
permissions:
  system.track:
    default: op
